package co.edu.unipiloto.signaltype;

import java.util.ArrayList;
import java.util.List;

public class SignExpert {

    List <String> getSigns(String typeSign){

        List<String> signs = new ArrayList<>();

        if(typeSign.equals("REGLAMENTARIAS")){
            signs.add("Altura máxima permitida");
            signs.add("Ancho máximo");
            signs.add("Ceda el paso");
            signs.add("Ciclovía");
            signs.add("Circulación con luces bajas");
            signs.add("Circulación no compartida");
            signs.add("Circulación prohibida a cabalgaduras");
            signs.add("Circulación prohibida de bicicletas");
            signs.add("Circulación prohibida de maquinaria agrícola");
            signs.add("Circulación prohibida de mascotas (ciclorutas)");
            signs.add("Circulación prohibida de motocicletas");
            signs.add("Circulación prohibida de peatones");
            signs.add("Circulación prohibida de vehículos automotores");
            signs.add("Circulación prohibida de vehículos de carga");
            signs.add("Conserve su derecha");
            signs.add("Descenso obligado");
            signs.add("Desvío");
            signs.add("Doble vía");
            signs.add("Espaciamiento");
            signs.add("Giro a la derecha solamente");
            signs.add("Giro a la izquierda solamente");
            signs.add("Iniciación de separador tránsito a la derecha");
            signs.add("Iniciación de separador tránsito a la izquierda");
            signs.add("No pase");
            signs.add("No parquear ni detenerse");
            signs.add("No pitar a la derecha");
            signs.add("Pare");
            signs.add("Paso uno a uno");
            signs.add("Peatones a la izquierda");
            signs.add("Permitido el cargue y descargue de mercancías");
            signs.add("Permitido recoger o dejar pasajeros");
            signs.add("Prohibido adelantar");
            signs.add("Prohibido el cambio de calzada");
            signs.add("Prohibido el cargue y descargue de mercancías");
            signs.add("Prohibido girar a la derecha");
            signs.add("Prohibido girar a la izquierda");
            signs.add("Prohibido parquear");
            signs.add("Prohibido recoger o dejar pasajeros");
            signs.add("Retén");
            signs.add("Sentido de circulación doble");
            signs.add("Sentido de circulación permitido");
            signs.add("Siga de frente");
            signs.add("Tres carriles (dos en contraflujo)");
            signs.add("Tres carriles (uno en contraflujo)");
            signs.add("Tránsito pesado");
            signs.add("Velocidad máxima");
            signs.add("Vía cerrada");
            signs.add("Zona estacionamiento de taxis");

        }else if (typeSign.equals("PREVENTIVAS")){
            signs.add("Abanderado");
            signs.add("Altura libre");
            signs.add("Altura máxima permitida");
            signs.add("Ancho libre");
            signs.add("Animales en la vía");
            signs.add("Barrera");
            signs.add("Bifurcación en “T”");
            signs.add("Bifurcación en “Y”");
            signs.add("Bifurcación derecha");
            signs.add("Bifurcación escalonada derecha-izquierda");
            signs.add("Bifurcación escalonada izquierda-derecha");
            signs.add("Bifurcación izquierda");
            signs.add("Ciclistas en la vía");
            signs.add("Circulación en dos sentidos");
            signs.add("Cruce a nivel con ferrocarril");
            signs.add("Curva peligrosa a la derecha");
            signs.add("Curva peligrosa a la izquierda");
            signs.add("Curva pronunciada a la derecha");
            signs.add("Curva pronunciada a la izquierda");
            signs.add("Curva y contracurva peligrosas derecha-izquierda");
            signs.add("Curva y contracurva peligrosas izquierda-derecha");
            signs.add("Curva y contracurva pronunciadas derecha-izquierda");
            signs.add("Curva y contracurva pronunciadas izquierda-derecha");
            signs.add("Descenso peligroso");
            signs.add("Descenso peligroso");
            signs.add("Ensanche de la calzada dos a cuatro carriles derecha");
            signs.add("Ensanche de la calzada dos a cuatro carriles izquierda");
            signs.add("Ensanche isométrico de la calzada");
            signs.add("Flecha direccional");
            signs.add("Final del pavimento");
            signs.add("Glorieta");
            signs.add("Iniciación de separador dos sentidos");
            signs.add("Iniciación de separador un sentido");
            signs.add("Incorporación de tránsito derecha");
            signs.add("Incorporación de tránsito izquierda");
            signs.add("Intersección de vías");
            signs.add("Maquinaria agrícola en la vía");
            signs.add("Maquinaria en la vía");
            signs.add("Paso a nivel");
            signs.add("Peatones en la vía");
            signs.add("Peso máximo total permitido");
            signs.add("Prevención de \"Ceda el paso\"");
            signs.add("Prevención de \"Pare\"");
            signs.add("Reducción asimétrica de calzada derecha");
            signs.add("Reducción asimétrica de calzada izquierda");
            signs.add("Reducción simétrica de la calzada");
            signs.add("Resalto");
            signs.add("Semáforo");
            signs.add("Superficie deslizante");
            signs.add("Superficie rizada");
            signs.add("Trabajos en la vía");
            signs.add("Tres carriles, uno en contraflujo");
            signs.add("Tres carriles, uno en contraflujo");
            signs.add("Túnel");
            signs.add("Vehículos en la vía (ciclorutas)");
            signs.add("Vía lateral derecha");
            signs.add("Vía lateral izquierda");
            signs.add("Zona de derrumbe");
            signs.add("Zona escolar");
            signs.add("Zona deportiva");
        }else{
            signs.add("Aeropuerto");
            signs.add("Aproximación obras en la vía");
            signs.add("Artesanías");
            signs.add("Bienes arqueológicos");
            signs.add("Cambio de moneda");
            signs.add("Carril cerrado (Derecho - centro - izquierdo)");
            signs.add("Cascada");
            signs.add("Centro");
            signs.add("Cicloparqueadero");
            signs.add("Cicloparqueadero");
            signs.add("Croquis de destino");
            signs.add("Cruce peatonal");
            signs.add("Descripción de giros");
            signs.add("Desvío");
            signs.add("Discapacitados");
            signs.add("Estación de servicio");
            signs.add("Estacionamiento de taxis");
            signs.add("Fin de la cicloruta");
            signs.add("Geográfica");
            signs.add("Iglesia");
            signs.add("Información confirmativa");
            signs.add("Información de decisión de destino");
            signs.add("Información fin de obra");
            signs.add("Información inicio de obra");
            signs.add("Información previa de destino en cicloruta");
            signs.add("Información preventiva");
            signs.add("Lago");
            signs.add("Marginal");
            signs.add("Monumento nacional");
            signs.add("Montallantas");
            signs.add("Museo");
            signs.add("Muelle");
            signs.add("Nomenclatura urbana");
            signs.add("Paradero de buses");
            signs.add("Parque");
            signs.add("Playa");
            signs.add("Polideportivo");
            signs.add("Poste de kilometraje");
            signs.add("Primeros auxilios");
            signs.add("Punto de información turística");
            signs.add("Restaurante");
            signs.add("Ruta departamental");
            signs.add("Ruta marginal de la selva");
            signs.add("Ruta nacional");
            signs.add("Ruta panamericana");
            signs.add("Seguridad vial");
            signs.add("Servicio sanitario");
            signs.add("Sitio de parqueo");
            signs.add("Teléfono");
            signs.add("Terminal");
            signs.add("Transbordador");
            signs.add("Transporte ferroviario");
            signs.add("Transporte masivo");
            signs.add("Vía para ciclistas");
            signs.add("Volcán");
            signs.add("Zona camping");
            signs.add("Zona militar");
            signs.add("Zonas especiales de parqueo");
            signs.add("Zona recreativa");
            signs.add("Zoológico");
        }
        return signs;
    }

}
